"""Verdict Agent — synthesises all agent signals into a final risk score.

If an LLM is configured, the synthesis text is generated by the model;
otherwise we use a deterministic template that combines all signals.
"""

from __future__ import annotations

import logging
from typing import Iterable

from app.agents.base import BaseAgent
from app.config import get_settings
from app.schemas.models import (
    AgentFinding,
    AgentName,
    AgentStatus,
    BoundingBox,
    PipelineState,
    Severity,
    VerdictResult,
    recommendation_for_score,
    status_for_score,
)
from app.services.llm import LLMClient

logger = logging.getLogger(__name__)


_SEVERITY_TO_SCORE = {
    Severity.LOW: 0.25,
    Severity.MEDIUM: 0.55,
    Severity.HIGH: 0.85,
}


class VerdictAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentName.VERDICT)
        self._llm = LLMClient()

    async def run(self, state: PipelineState) -> PipelineState:
        self._mark(state, AgentStatus.RUNNING)
        try:
            settings = get_settings()
            findings = self._collect_findings(state)
            weights = {
                AgentName.FORENSICS: settings.weight_forensics,
                AgentName.POLICY: settings.weight_policy,
                AgentName.HISTORY: settings.weight_history,
                AgentName.RING: settings.weight_ring,
            }
            weighted = sum(
                findings[a].score * w for a, w in weights.items()
            )
            risk_score = int(round(weighted * 100))

            # Deterministic escalation. An internal arithmetic contradiction
            # (the printed total does not reconcile with the line items) is, by
            # itself, strong evidence of post-issuance editing. Such a structural
            # fault is surfaced for human review regardless of whether the other
            # agents happened to corroborate it — it must never be averaged away.
            if state.forensics is not None and any(
                f.code == "semantic_conflict" and f.severity == Severity.HIGH
                for f in state.forensics.flags
            ):
                risk_score = max(risk_score, 75)

            recommendation = recommendation_for_score(risk_score)

            summary = await self._synthesise(state, findings, risk_score)

            state.verdict = VerdictResult(
                risk_score=risk_score,
                recommendation=recommendation,
                summary=summary,
                findings=[
                    findings[a]
                    for a in (
                        AgentName.FORENSICS,
                        AgentName.POLICY,
                        AgentName.HISTORY,
                        AgentName.RING,
                    )
                    if a in findings
                ],
            )

            if risk_score >= 75:
                self._mark(state, AgentStatus.HIGH)
            elif risk_score >= 50:
                self._mark(state, AgentStatus.REVIEW)
            else:
                self._mark(state, AgentStatus.PASSED)
        except Exception as exc:
            logger.exception("verdict failed")
            state.errors[self.name.value] = str(exc)
            self._mark(state, AgentStatus.ERROR)
        return state
    def _collect_findings(self, state: PipelineState) -> dict[AgentName, AgentFinding]:
        findings: dict[AgentName, AgentFinding] = {}

        if state.forensics is not None:
            findings[AgentName.FORENSICS] = AgentFinding(
                agent=AgentName.FORENSICS,
                status=status_for_score(state.forensics.composite_score),
                score=state.forensics.composite_score,
                headline=self._forensics_headline(state),
                detail="; ".join(f.label for f in state.forensics.flags)
                or "no anomalies detected",
            )
        else:
            findings[AgentName.FORENSICS] = AgentFinding(
                agent=AgentName.FORENSICS,
                status=AgentStatus.ERROR,
                score=0.0,
                headline="Forensics unavailable",
                detail="",
            )

        if state.policy is not None:
            findings[AgentName.POLICY] = AgentFinding(
                agent=AgentName.POLICY,
                status=status_for_score(state.policy.score),
                score=state.policy.score,
                headline=self._policy_headline(state),
                detail=state.policy.rationale or "no policy clauses cited",
            )
        else:
            findings[AgentName.POLICY] = AgentFinding(
                agent=AgentName.POLICY,
                status=AgentStatus.ERROR,
                score=0.0,
                headline="Policy check unavailable",
                detail="",
            )

        if state.history is not None:
            findings[AgentName.HISTORY] = AgentFinding(
                agent=AgentName.HISTORY,
                status=status_for_score(state.history.score),
                score=state.history.score,
                headline=self._history_headline(state),
                detail="; ".join(f.label for f in state.history.flags)
                or "vendor history consistent",
            )
        else:
            findings[AgentName.HISTORY] = AgentFinding(
                agent=AgentName.HISTORY,
                status=AgentStatus.ERROR,
                score=0.0,
                headline="Vendor history unavailable",
                detail="",
            )

        if state.ring is not None:
            findings[AgentName.RING] = AgentFinding(
                agent=AgentName.RING,
                status=status_for_score(state.ring.score),
                score=state.ring.score,
                headline=self._ring_headline(state),
                detail=(
                    f"{len(state.ring.matches)} match(es) across "
                    f"{state.ring.total_indexed} indexed documents"
                ),
            )
        else:
            findings[AgentName.RING] = AgentFinding(
                agent=AgentName.RING,
                status=AgentStatus.ERROR,
                score=0.0,
                headline="Ring detection unavailable",
                detail="",
            )
        return findings

    # ------------------------------------------------------------------- #

    async def _synthesise(
        self,
        state: PipelineState,
        findings: dict[AgentName, AgentFinding],
        risk_score: int,
    ) -> str:
        system = (
            "You are the Verdict Agent of DocForensic AI. "
            "You write a concise, evidence-cited summary explaining a fraud-risk "
            "verdict on a single invoice or receipt. Be specific, name the agents "
            "that flagged the document, and never speculate beyond the evidence."
        )
        flags = self._collect_flag_text(state)
        user = (
            f"Document: {state.filename}\n"
            f"Risk score: {risk_score}/100\n\n"
            f"Agent findings:\n"
            + "\n".join(f"- {a.value}: {f.headline} (score={f.score:.2f})" for a, f in findings.items())
            + f"\n\nForensic flags:\n{flags}\n\n"
            + f"Multimodal signal fusion:\n{self._fusion_text(state)}\n\n"
            + f"Cross-modal consistency check:\n{self._cross_modal_text(state)}\n\n"
            + "Write a 3-5 sentence plain-English summary explaining the verdict "
            "and the evidence behind it. Where two sources disagree — for example "
            "when the printed total conflicts with the line items, or when a "
            "clean-looking page carries tamper saliency on the total field — call "
            "that contradiction out explicitly."
        )
        return await self._llm.chat(system, user)

    @staticmethod
    def _fusion_text(state: PipelineState) -> str:
        """Render the six-signal fusion breakdown for the LLM and the audit trail."""
        fusion = state.forensics.fusion if state.forensics else None
        if fusion is None:
            return "  (signal fusion unavailable)"
        lines = [
            f"  • {c.label}: {c.value:.2f} x weight {c.weight:.2f} "
            f"= {c.contribution:.3f}"
            for c in fusion.contributions
        ]
        lines.append(f"  • fused score {fusion.score:.3f} -> band '{fusion.band}'")
        if fusion.missing:
            lines.append(f"  • unavailable signals: {', '.join(fusion.missing)}")
        return "\n".join(lines)

    @staticmethod
    def _cross_modal_text(state: PipelineState) -> str:
        """Compare what the document *says* against what the evidence *shows*.

        This is the DocForensic equivalent of the step the AWS IDP guidance
        delegates to a Bedrock foundation model: consolidate the OCR text, the
        image-analysis results and the vendor context, then look for
        contradictions between them. We assemble the contradictions
        deterministically here so the LLM is asked to interpret evidence rather
        than to invent it.
        """
        lines: list[str] = []
        extraction = state.extraction
        forensics = state.forensics
        history = state.history

        if extraction is None:
            return "  (no extracted record to cross-check)"

        lines.append(
            f"  • Document states: vendor={extraction.vendor!r}, "
            f"invoice={extraction.invoice_number!r}, "
            f"date={extraction.invoice_date!r}, "
            f"total={extraction.total_amount!r} {extraction.currency}"
        )

        line_sum = sum(float(i.amount or 0.0) for i in extraction.line_items)
        if extraction.line_items and extraction.total_amount is not None:
            gap = line_sum - float(extraction.total_amount)
            if abs(gap) > 0.02:
                lines.append(
                    f"  • CONTRADICTION: line items sum to {line_sum:.2f} but the "
                    f"printed total is {float(extraction.total_amount):.2f} "
                    f"(gap {gap:+.2f})."
                )

        if forensics is not None:
            local = forensics.patch_localization
            if local is not None and local.matched_fields:
                fields = ", ".join(f.replace("_", " ") for f in local.matched_fields)
                lines.append(
                    f"  • Visual anomaly overlaps the {fields} "
                    f"(overlap {local.overlap_score:.2f})."
                )
            if forensics.saliency is not None:
                band = forensics.fusion.band if forensics.fusion else "n/a"
                lines.append(
                    f"  • Tamper saliency {forensics.saliency.score:.2f} "
                    f"(fused band '{band}')."
                )
            if forensics.uncertainty is not None:
                lines.append(
                    f"  • Detector stability: confidence "
                    f"{forensics.uncertainty.confidence:.2f} "
                    f"across {forensics.uncertainty.passes} passes."
                )
            if forensics.composite_score < 0.4 and (
                forensics.saliency is not None and forensics.saliency.score >= 0.55
            ):
                lines.append(
                    "  • CONTRADICTION: the page looks forensically clean overall "
                    "but saliency is concentrated on a single region."
                )

        if (
            history is not None
            and extraction.total_amount is not None
            and history.vendor_prior_submissions
            and history.vendor_max_amount
        ):
            ratio = float(extraction.total_amount) / max(history.vendor_max_amount, 1e-6)
            if ratio > 1.5:
                lines.append(
                    f"  • This claim is {ratio:.1f}x the vendor's previous "
                    f"maximum of {history.vendor_max_amount:.2f}."
                )
        if history is not None and any(f.code == "bank_account_changed" for f in history.flags):
            lines.append(
                f"  • CRITICAL PAYMENT RISK: Known vendor '{extraction.vendor}' suddenly changed its designated bank account."
            )

        if state.ring is not None and state.ring.shared_routing_matches:
            first = state.ring.shared_routing_matches[0]
            lines.append(
                f"  • SHELL VENDOR RING: Shares identical bank routing number with vendor '{first.matched_vendor}'."
            )

        return "\n".join(lines) or "  (no cross-modal contradictions detected)"

    @staticmethod
    def _collect_flag_text(state: PipelineState) -> str:
        bits: list[str] = []
        if state.forensics:
            for flag in state.forensics.flags:
                bits.append(f"  • [{flag.severity.value}] {flag.label}: {flag.detail}")
        if state.policy and state.policy.violated_clauses:
            for clause in state.policy.violated_clauses:
                bits.append(f"  • [policy:{clause.clause_id}] {clause.clause_title} — {clause.snippet}")
        if state.history:
            for flag in state.history.flags:
                bits.append(f"  • [{flag.severity.value}] {flag.label}: {flag.detail}")
        if state.ring:
            if state.ring.shared_routing_matches:
                for m in state.ring.shared_routing_matches[:2]:
                    bits.append(
                        f"  • [CRITICAL] Shell vendor ring: identical routing ({m.shared_routing_number}) with vendor '{m.matched_vendor}'"
                    )
            for m in state.ring.matches[:3]:
                if not m.shared_routing:
                    bits.append(f"  • [ring] Cloned template (dist={m.hamming_distance}) → {m.matched_vendor or m.matched_filename}")
        return "\n".join(bits) or "  (no specific flags)"

    @staticmethod
    def _forensics_headline(state: PipelineState) -> str:
        fr = state.forensics
        if fr is None or not fr.flags:
            return "Document image shows no obvious tampering"
        top = max(fr.flags, key=lambda f: _SEVERITY_TO_SCORE[f.severity])
        if fr.flagged_region:
            box: BoundingBox | None = fr.flagged_region
            return (
                f"Document shows evidence of post-issuance editing "
                f"around the invoice total"
                if box else top.label
            )
        return top.label

    @staticmethod
    def _policy_headline(state: PipelineState) -> str:
        pr = state.policy
        if pr is None or not pr.violated_clauses:
            return "Within expense policy"
        top = max(pr.violated_clauses, key=lambda c: c.relevance)
        return f"Violates {top.clause_id}: {top.clause_title}"

    @staticmethod
    def _history_headline(state: PipelineState) -> str:
        hr = state.history
        if hr is None:
            return "Vendor history unavailable"
        if hr.vendor_prior_submissions == 0:
            return "Vendor not previously seen"
        if not hr.flags:
            return "Vendor has consistent submission history"
        # Prioritize bank account change over amount/frequency spikes
        for f in hr.flags:
            if f.code == "bank_account_changed":
                return "CRITICAL: Sudden bank account change detected"
        return hr.flags[0].label

    @staticmethod
    def _ring_headline(state: PipelineState) -> str:
        rr = state.ring
        if rr is None or not rr.matches:
            return "No cross-document fingerprint match"
        if rr.shared_routing_matches:
            first = rr.shared_routing_matches[0]
            return f"Syndicate Alert: Shared routing with '{first.matched_vendor}'"
        n = len(rr.matches)
        return f"Cloned template match across {n} document{'s' if n != 1 else ''} from separate vendors"